[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python3 scraper.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[cron]
# Run scraper every 12 hours
scraper = "0 */12 * * * python3 scraper.py --validate-existing"
