feeds:
  - name: "NSF"
    url: "https://www.nsf.gov/rss/rss_www_funding.xml"
    category: "NSF Funding"
  - name: "NIH"
    url: "https://grants.nih.gov/grants/guide/WeeklyIndex.cfm?RSSFeed=FundingOpportunities"
    category: "NIH Funding"

  # Broad discovery via web search
  - name: "Global grant discovery"
    type: search
    queries:
      - 'site:.gov (grant OR "funding opportunity" OR NOFO OR FOA) (apply OR application)'
      - 'site:.edu (grant OR fellowship) (RFP OR "call for proposals" OR apply)'
      - 'site:.org (grant OR "apply for a grant") ("program" OR "guidelines")'
      - 'foundation (grant guidelines OR "how to apply" OR "grant program")'
      - 'site:.int (grant OR funding) (apply OR application)'
    max_results_per_query: 50
    same_host_only: false
    include_patterns: ["/grant", "/funding", "/opportunit", "/rfp", "/apply", "/nofo", "/foa"]
    rules:
      title: { css: "h1, h2" }
      description: { css: "main, article, .content" }
      deadline:
        css: "*"
        regex: "(Deadline|Due|Close(s|d)? on)[:\\s]+([^<\\n]+)"
      amount:
        css: "*"
        regex: "([$€£]\\s?\\d[\\d,\\.]*)(?:\\s?[–-]\\s?([$€£]\\s?\\d[\\d,\\.]*))?"
    limit: 250

defaults:
  currency: "USD"
