# Add/remove feeds anytime. source must be unique per feed.
feeds:
  - source: "nsf"
    url: "https://www.nsf.gov/rss/rss_www_funding.xml"
    category: "NSF Funding"
  - source: "nih"
    url: "https://grants.nih.gov/grants/guide/WeeklyIndex.cfm?RSSFeed=FundingOpportunities"
    category: "NIH Funding"
# Optional: fallback defaults if feed doesn’t provide them
defaults:
  currency: "USD"
